### ISSUE TITLE
Stupid layman's question

### ISSUE THREAD

**Issue by Trohed** [RCInet/LastEpoch_Mods#6]
First of all, a huge thank you for the great job.

The solution is probably trivial, but I can't deal with it... previous versions compiled correctly, but the changes from yesterday and today do not want to compile correctly and messages appear.

what am I doing wrong or what I don't have installed, please help and be understanding for a layman

> 
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeContent' and no accessible extension method 'activeContent' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	109	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeContent' and no accessible extension method 'activeContent' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	111	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeParameters' and no accessible extension method 'activeParameters' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	112	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeParameters' and no accessible extension method 'activeParameters' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	114	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeParameters' and no accessible extension method 'activeParameters' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	114	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeParameters' and no accessible extension method 'activeParameters' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	119	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeParameters' and no accessible extension method 'activeParameters' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	122	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeParameters' and no accessible extension method 'activeParameters' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	127	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeParameters' and no accessible extension method 'activeParameters' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	137	Active
Error	CS1061	'TooltipItemManager' does not contain a definition for 'activeContent' and no accessible extension method 'activeContent' accepting a first argument of type 'TooltipItemManager' could be found (are you missing a using directive or an assembly reference?)	LastEpoch_Hud	Q:\!gry\!projekt\LastEpoch_Mods-3.2.3-ML-0.5.7-nowe\LastEpoch_Hud\Scripts\Mods\Items\Items_Tooltip.cs	139	Active

**Comment by RCInet** [comment]
Added in LastEpoch 1.0.7.1

**Comment by Trohed** [comment]
> Added in LastEpoch 1.0.7.1

thank you... it helped :)

my mistake... I was using files from the previous version
